[build]
  command = "npm ci && npm run build"
  publish = "build"
  node_version = "20"

[functions]
  directory = "netlify/functions"

# Proxy del front a la Function
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
